
services:
  postgres:
    image: postgres:latest
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: todo


  web:
    build: .
    container_name: web
    command: bash -c "python manage.py makemigrations --empty main &&
                      python manage.py makemigrations &&
                      python manage.py migrate &&
                      gunicorn todo.wsgi --bind 0.0.0.0:8000 --workers 4"
    depends_on:
      - postgres
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    depends_on:
      - web
